
#Nina Maller                                                                    
#Lab 1a                                                                         
#SID: 604955977  
#nina.maller@gmail.com                                                               

.SILENT:

default:
	gcc lab1a.c -o lab1a
clean:
	rm -f lab1a *.txt *.o *.gz
dist:
	tar -czf lab1a-604955977.tar.gz lab1a.c Makefile README
